Lead7.Olimpus.Web/Models/Config/Empresa/EmpresaModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Lead7.Olimpus.Web.Models.Config.Modulo;
using Lead7.Olimpus.Web.Models.Config.Perfil;

namespace Lead7.Olimpus.Web.Models.Config.Empresa
{
    public class EmpresaModel : ModelBase
    {
        public int Id { get; set; }

        [Required]
        public string NomeEmpresa { get; set; }

        public byte[] Logotipo { get; set; }

        public IList<PerfilModel> Perfis { get; set; }

        public IList<ModuloModel> Modulos { get; set; } 

        public IList<SelectListItem> ListaPerfis { get; set; } 

        public IList<SelectListItem> ListaModulos { get; set; } 

        public EmpresaModel()
        {
            Perfis = new List<PerfilModel>();
            Modulos = new List<ModuloModel>();
            ListaPerfis = new List<SelectListItem>();
            ListaModulos = new List<SelectListItem>();
        }
    }
}

Lead7.Olimpus.Web/Controllers/Config/Empresa/EmpresaController.cs
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Castle.Core.Internal;
using Lead7.Olimpus.Service.Interfaces.Config;
using Lead7.Olimpus.Web.Models.Config.Empresa;
using Lead7.Olimpus.Web.Models.Config.Modulo;
using Lead7.Olimpus.Web.Models.Config.Perfil;

namespace Lead7.Olimpus.Web.Controllers.Config.Empresa
{
    public class EmpresaController : ControllerBase
    {
        private readonly IEmpresaService _companyService;
        private readonly IPerfilService _perfilService;
        private readonly IModuloService _moduloService;

        public EmpresaController(IEmpresaService companyService, IPerfilService perfilService, IModuloService moduloService)
        {
            _companyService = companyService;
            _perfilService = perfilService;
            _moduloService = moduloService;
        }

        public ActionResult Index()
        {
            var session = (Domain.Config.Usuario)Session["Login"];

            if (!this.User.Identity.IsAuthenticated || session == null) return Logout();

            var model =
                _companyService.GetEmpresas()
                    .Select(
                        x =>
                            new EmpresaModel()
                            {
                                Id = x.Id,
                                NomeEmpresa = x.Nome,
                                Logotipo = x.Logotipo,
                                Perfis = x.Perfis.Select(y => new PerfilModel() { Id = y.Id, Nome = y.Nome }).ToList(),
                                Modulos = x.Modulos.Select(y => new ModuloModel() { Id = y.Id, Nome = y.Nome, Descricao = y.Descricao }).ToList()
                            })
                    .ToList();

            return View(model);
        }

        public ActionResult Create()
        {
            var session = (Domain.Config.Usuario)Session["Login"];

            if (!this.User.Identity.IsAuthenticated || session == null) return Logout();

            var model = new EmpresaModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(EmpresaModel model)
        {
            var session = (Domain.Config.Usuario)Session["Login"];

            if (!this.User.Identity.IsAuthenticated || session == null) return Logout();

            var data = new byte[] { };

            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                var pic = System.Web.HttpContext.Current.Request.Files["imgBtn"];

                using (var inputStream = pic.InputStream)
                {
                    var memoryStream = inputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        inputStream.CopyTo(memoryStream);
                    }
                    data = memoryStream.ToArray();
                    model.Logotipo = data;
                }
            }

            _companyService.Create(new Domain.Config.Empresa() { Logotipo = model.Logotipo, Nome = model.NomeEmpresa });

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var session = (Domain.Config.Usuario)Session["Login"];

            if (!this.User.Identity.IsAuthenticated || session == null) return Logout();

            var qry = _companyService.GetEmpresa(id);
            var model = new EmpresaModel()
            {
                Id = qry.Id,
                Logotipo = qry.Logotipo,
                NomeEmpresa = qry.Nome,
                Perfis = qry.Perfis.Select(x => new PerfilModel() { Id = x.Id, Nome = x.Nome}).ToList(),
                Modulos = qry.Modulos.Select(x => new ModuloModel() { Id = x.Id, Nome = x.Nome, Descricao = x.Descricao, PodeExcluir = x.PodeExcluir }).ToList(),
                ListaPerfis = _perfilService.GetPerfis().Select(x => new SelectListItem() { Text = x.Nome, Value = x.Id.ToString() }).ToList(),
            };

            model.ListaModulos = _moduloService.GetModulos().Where(w => model.Modulos.All(p => p.Id != w.Id)).Select(x => new SelectListItem() { Text = x.Nome, Value = x.Id.ToString() }).ToList();

            model.ListaPerfis.Insert(0, new SelectListItem() { Value = "0", Text = "" });
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EmpresaModel model)
        {
            var session = (Domain.Config.Usuario)Session["Login"];

            if (!this.User.Identity.IsAuthenticated || session == null) return Logout();

            var data = new byte[] { };
            var obj = _companyService.GetEmpresa(model.Id);

            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                var pic = System.Web.HttpContext.Current.Request.Files["imgBtn"];

                using (var inputStream = pic.InputStream)
                {
                    var memoryStream = inputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        inputStream.CopyTo(memoryStream);
                    }
                    data = memoryStream.ToArray();
                    model.Logotipo = data;
                }
            }

            obj.Logotipo = model.Logotipo;
            obj.Nome = model.NomeEmpresa;

            _companyService.Update(obj);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var session = (Domain.Config.Usuario)Session["Login"];

            if (!this.User.Identity.IsAuthenticated || session == null) return Logout();

            _companyService.Delete(id);

            var model = _companyService.GetEmpresas().Select(x => new EmpresaModel() { Id = x.Id, NomeEmpresa = x.Nome, Logotipo = x.Logotipo }).ToList();

            return PartialView("Index", model);
        }

        [HttpPost]
        public ActionResult AddPerfil(int id)
        {
            var session = (Domain.Config.Usuario)Session["Login"];

            if (!this.User.Identity.IsAuthenticated || session == null) return Logout();

            var result = _perfilService.GetPerfil(id);
            var qry = _companyService.GetEmpresa(id);

            if (!qry.Perfis.Contains(result))
            {
                qry.Perfis.Add(result);
                _companyService.Update(qry);
            }

            var model = new EmpresaModel()
            {
                Id = qry.Id,
                Logotipo = qry.Logotipo,
                NomeEmpresa = qry.Nome,
                Perfis = qry.Perfis.Select(x => new PerfilModel() { Id = x.Id, Nome = x.Nome }).ToList(),
                ListaPerfis = _perfilService.GetPerfis().Select(x => new SelectListItem() { Text = x.Nome, Value = x.Id.ToString() }).ToList()
            };

            model.ListaPerfis.Insert(0, new SelectListItem() { Value = "0", Text = "" });            
            return PartialView("Perfil/Index", model);
        }

        [HttpPost]
        public ActionResult DeleteModulo(int idModulo, int idEmpresa)
        {
            var model = _companyService.GetEmpresas().Select(x => new EmpresaModel() { Id = x.Id, NomeEmpresa = x.Nome, Logotipo = x.Logotipo }).ToList();

            return PartialView("Index", model);
        }
    }
}

Lead7.Olimpus.Web/Views/Empresa/Create.cshtml
@model Lead7.Olimpus.Web.Models.Config.Empresa.EmpresaModel
@using Lead7.Olimpus.Web.Providers
@using MyResources = Lead7.Olimpus.Web.Resources

<div class="col-md-12 col-sm-12 col-xs-12" style="width: 70%">
    <div class="x_panel">
        <div class="x_title">
            <h2>@MyResources.Empresa.TituloNovo</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @using (Html.BeginForm("Create", "Empresa", FormMethod.Post, new { @id = "frmNew", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                    <div class="form-group">
                        @Html.Label(MyResources.Empresa.NomeEmpresa, new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NomeEmpresa, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.NomeEmpresa, "", new {@class = "text-danger"})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label(MyResources.Empresa.Logotipo, new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.FilePicker("imgBtn", FilterFileType.Image, new { @class="find filestyle custom-file-input" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <a href="#" id="btnSalvar" title="@MyResources.Empresa.Salvar" class="btn btn-app">
                                <i class="fa fa-save"></i>
                                <span class="body-content"> @MyResources.Empresa.Salvar</span>
                            </a>
                            <a href="@Url.Action("Index", "Empresa")" title="@MyResources.Empresa.Voltar" class="btn btn-app">
                                <i class="glyphicon glyphicon-log-out"></i>
                                <span class="body-content"> @MyResources.Empresa.Voltar</span>
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript" src="~/Scripts/bootstrap-filestyle.js"> </script>
    <script>
        $(document).ready(function () {
            var data = new FormData();

            $('#btnSalvar').click(function (e) {
                e.preventDefault();
                $('#frmNew').submit();
            });

            $('input[type=file]').change(function () {
                var files = $('.find').get(0).files;
                if (files.length > 0) {
                    data.append('imgBtn', files[0]);
                }
            });
        });
    </script>
}

Lead7.Olimpus.Web/Views/Empresa/Edit.cshtml
@model Lead7.Olimpus.Web.Models.Config.Empresa.EmpresaModel
@using Lead7.Olimpus.Web.Providers
@using MyResources = Lead7.Olimpus.Web.Resources

<div class="col-md-12 col-sm-12 col-xs-12" style="width: 70%">
    <div class="x_panel">
        <div class="x_title">
            <h2>@MyResources.Empresa.TituloEditar</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            @using (Html.BeginForm("Edit", "Empresa", FormMethod.Post, new { @id = "frmEdit", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label(MyResources.Empresa.NomeEmpresa, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NomeEmpresa, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NomeEmpresa, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label(MyResources.Empresa.Logotipo, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.FilePicker("imgBtn", FilterFileType.Image, new { @class = "find filestyle custom-file-input" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="x_panel">
                            <div class="x_content">

                                <div class="" role="tabpanel" data-example-id="togglable-tabs">
                                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                        <li role="presentation" class="active">
                                            <a href="#tab_content1" id="perfil-tab" role="tab" data-toggle="tab" aria-expanded="true">@MyResources.Empresa.Perfil</a>
                                        </li>
                                        <li role="presentation" class="">
                                            <a href="#tab_content2" role="tab" id="modulo-tab" data-toggle="tab" aria-expanded="false">@MyResources.Empresa.Modulos</a>
                                        </li>
                                    </ul>
                                    <div id="myTabContent" class="tab-content">
                                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="perfil-tab">
                                            @Html.Partial("Perfil/Index", Model)
                                        </div>
                                        <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="modulo-tab">
                                            @Html.Partial("Modulo/Index", Model)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-0 col-md-10">
                            <a href="#" id="btnSalvar" title="@MyResources.Empresa.Salvar" class="btn btn-app">
                                <i class="fa fa-save"></i>
                                <span class="body-content"> @MyResources.Empresa.Salvar</span>
                            </a>
                            <a href="@Url.Action("Index", "Empresa")" title="@MyResources.Empresa.Voltar" class="btn btn-app">
                                <i class="glyphicon glyphicon-log-out"></i>
                                <span class="body-content"> @MyResources.Empresa.Voltar</span>
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript" src="~/Scripts/bootstrap-filestyle.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-typeahead.js"></script>

    <script>
        $(document).ready(function() {
            var data = new FormData();

            $('#btnSalvar').click(function(e) {
                e.preventDefault();
                $('#frmEdit').submit();
            });

            $('input[type=file]').change(function() {
                var files = $('.find').get(0).files;
                if (files.length > 0) {
                    data.append('imgBtn', files[0]);
                }
            });

            $('#btnAddPerfil').click(function() {
                var request = $.ajax({
                    url: '@Url.Content("../AddPerfil")',
                    method: 'POST',
                    data: { id: $('#ddlPerfis').val() },
                    dataType: 'html'
                });

                request.done(function (data) {
                    $('#tab_content1').html(data);
                    Lobibox.notify('success', {
                        title: '@MyResources.Layout.Sucesso',
                        msg: '@MyResources.Layout.MsgInsOK'
                    });
                });

                request.fail(function (jqXHR, textStatus) {
                    Lobibox.notify('error', {
                        title: '@MyResources.Layout.Erro',
                        msg: textStatus
                    });
                });
            });
        });
    </script>
}

Lead7.Olimpus.Web/Views/Empresa/Index.cshtml
@using MyResources = Lead7.Olimpus.Web.Resources
@model IList<Lead7.Olimpus.Web.Models.Config.Empresa.EmpresaModel>

<div id="divEmpresas" class="col-md-12 col-sm-12 col-xs-12" style="width: 80%">
    <div class="x_panel">
        <div class="x_title">
            <h2>@MyResources.Empresa.Titulo</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table class="table table-striped responsive-utilities jambo_table bulk_action">
                <thead>
                <tr class="headings">
                    <th class="column-title" style="width: 10%">ID </th>
                    <th class="column-title" style="width: 20%">@MyResources.Empresa.Logotipo </th>
                    <th class="column-title" >@MyResources.Empresa.NomeEmpresa </th>
                    <th class="column-title no-link last" style="text-align: center; width: 20%">
                        <span class="nobr">@MyResources.Layout.Action</span>
                    </th>
                </tr>
                </thead>
                <tbody>
                @if (!Model.Any())
                {
                    <tr class="even pointer">
                        <td class="a-center" colspan="5">@MyResources.Empresa.SemRegistros</td>
                    </tr>
                }
                else
                {
                    foreach (var item in Model)
                    {
                        var base64 = Convert.ToBase64String(item.Logotipo);
                        var imgSrc = base64 == "" ? Url.Content("~/images/no-images.png") : String.Format("data:image/png;base64,{0}", base64);

                        <tr class="even pointer">
                            <td class=" " style="vertical-align: middle">@item.Id</td>
                            <td class=" " style="vertical-align: middle"><img src="@imgSrc" alt="" style="width: 120px; height: 80px"/> </td>
                            <td class=" " style="vertical-align: middle">@item.NomeEmpresa </td>
                            <td class=" last" style="text-align: center; vertical-align: middle">
                                <a href="/Empresa/Edit/@item.Id" title="@MyResources.Layout.View" class="btn btn-default btn-group-xs"><i class="fa fa-edit"></i> @MyResources.Layout.View</a>
                                <a href="#" onclick="javascript: confirmar(@item.Id);" title="@MyResources.Layout.Delete" class="btn btn-default btn-group-xs"><i class="fa fa-remove"></i> @MyResources.Layout.Delete</a>
                            </td>
                        </tr>
                    }
                }
                </tbody>
            </table>
            <a href="@Url.Action("Create", "Empresa")" title="@MyResources.Empresa.Novo" class="btn btn-default submit">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="body-content"> @MyResources.Empresa.Novo</span>
            </a>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        function confirmar(value) {
            Lobibox.confirm({
                msg: '@MyResources.Empresa.MsgConfirm',
                title: '@MyResources.Empresa.Titulo',
                buttons: {
                    yes: {
                        'class': 'lobibox-btn lobibox-btn-yes',
                        text: '@MyResources.Layout.Yes',
                        closeOnClick: true
                    },
                    no: {
                        'class': 'lobibox-btn lobibox-btn-no',
                        text: '@MyResources.Layout.No',
                        closeOnClick: true
                    }
                },
                callback: function(lobibox, type) {
                    if (type === 'yes') {
                        var request = $.ajax({
                            url: '@Url.Content("../Empresa/Delete")',
                            method: 'POST',
                            data: { id: value },
                            dataType: 'html'
                        });

                        request.done(function(data) {
                            $('#main').html(data);
                            Lobibox.notify('success', {
                                title: '@MyResources.Layout.Sucesso',
                                msg: '@MyResources.Layout.MsgDelOK'
                            });
                        });

                        request.fail(function(jqXHR, textStatus) {
                            Lobibox.notify('error', {
                                title: '@MyResources.Layout.Erro',
                                msg: textStatus
                            });
                        });
                    }
                }
            });
        }

        function excluirmodulo(idmodulo, idempresa) {
            Lobibox.confirm({
                msg: '@MyResources.Modulo.MsgConfirm',
                title: '@MyResources.Empresa.Titulo',
                buttons: {
                    yes: {
                        'class': 'lobibox-btn lobibox-btn-yes',
                        text: '@MyResources.Layout.Yes',
                        closeOnClick: true
                    },
                    no: {
                        'class': 'lobibox-btn lobibox-btn-no',
                        text: '@MyResources.Layout.No',
                        closeOnClick: true
                    }
                },
                callback: function (lobibox, type) {
                    if (type === 'yes') {
                        var request = $.ajax({
                            url: '@Url.Content("../Empresa/DeleteModulo")',
                            method: 'POST',
                            data: { idModulo: idmodulo, idEmpresa: idempresa },
                            dataType: 'html'
                        });

                        request.done(function (data) {
                            $('#main').html(data);
                            Lobibox.notify('success', {
                                title: '@MyResources.Layout.Sucesso',
                                msg: '@MyResources.Layout.MsgDelOK'
                            });
                        });

                        request.fail(function (jqXHR, textStatus) {
                            Lobibox.notify('error', {
                                title: '@MyResources.Layout.Erro',
                                msg: textStatus
                            });
                        });
                    }
                }
            });
        }

        function habilitarmodulo(idmodulo, idempresa) {
            
        }

        function registrarmodulo(idmodulo, idempresa) {

        }
    </script>
}